#!/usr/bin/env python

from sklearn.cluster import KMeans
import time
import matplotlib.pyplot as plt
import numpy as np


from SimpleCV import Image,Camera,Display,Image,Color
from SimpleCV import *
import cv2

import cv
import cv2
import time
import numpy as np
from PIL import Image
#cargar las dos imagenes desde el directorio donde estoy ejecutando el Script
cam0=SimpleCV.Camera(0)
cam1=SimpleCV.Camera(1)



im1 =cam0.getImage()
im1.save("foto1.jpg")
foto=im1.show()
time.sleep(3)

im2 =cam1.getImage()
im2.save("foto2.jpg")
foto=im2.show()
time.sleep(3)

#img1=Image("foto2.jpg")
img2=rotate(73.99,point=(im2.width/2, im2.height/2))
img3=rotate(73.00, fixex=False, point=(im2.widht/2, im2.height/2))
img4=img2.sideBySide(img3)
foto=img4.show()
